[project]
authors = ["SamueleSoraggi <samuelson1990@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "ABC13-bulkrna-deconvolution"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
r-seurat = { version = ">=5.1.0,<6", channel = "conda-forge" }
r-remotes = { version = ">=2.5.0,<3", channel = "conda-forge" }
r-base = { version = ">=4.4.2,<4.5", channel = "conda-forge" }
r-devtools = { version = ">=2.4.5,<3", channel = "conda-forge" }
r-dplyr = { version = ">=1.1.4,<2", channel = "conda-forge" }
jupyterlab = ">=4.3.5,<5"
r-irkernel = ">=1.3.2,<2"
libzlib = ">=1.3.1,<2"
zlib = ">=1.3.1,<2"
r-readxl = ">=1.4.3,<2"
bioconductor-biomart = { version = ">=2.62.0,<3", channel = "bioconda" }
